# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5IumHdEATk_SZzzmYJKOmcgtGuhtaC8
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import pandas as pd
import matplotlib.pyplot as plt

from llm_analysis import client


def detect_relevant_column(question, columns):

    prompt = f"""
    You are a data analyst.

    User Question:
    {question}

    Dataset Columns:
    {list(columns)}

    IMPORTANT:
    Return ONLY ONE exact column name.

    Do NOT explain.
    Do NOT use bullet points.
    Do NOT use sentences.
    Return ONLY the raw column name.
    """

    response = client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.choices[0].message.content.strip()

# ==========================================
# Overall Sales Analysis
# ==========================================

def analyze_overall_sales(df, schema):

    sales_col = schema["sales"]

    profit_col = schema["profit"]

    order_col = schema.get("order")

    # --------------------------------------
    # Total Sales
    # --------------------------------------

    total_sales = (
        df[sales_col].sum()
        if sales_col is not None
        else None
    )

    # --------------------------------------
    # Total Profit
    # --------------------------------------

    if profit_col is not None:

        total_profit = df[profit_col].sum()

        profit_margin = (
            total_profit / total_sales
            if total_sales != 0
            else None
        )

    else:

        total_profit = "Not Available"

        profit_margin = "Not Available"

    # --------------------------------------
    # Average Order Value
    # --------------------------------------

    if order_col is not None:

        aov = (
            df[sales_col].sum() /
            df[order_col].nunique()
        )

    else:

        aov = "Not Available"

    # --------------------------------------
    # Return
    # --------------------------------------

    return {

        "total_sales": total_sales,

        "total_profit": total_profit,

        "profit_margin": profit_margin,

        "avg_order_value": aov
    }

# ==========================================
# Time Trend Analysis
# ==========================================

def analyze_monthly_sales_trend(df, schema):

    sales_col = schema["sales"]

    date_col = schema["date"]


    if sales_col is None or date_col is None:

        return "Required columns not available."


    df[date_col] = pd.to_datetime(
        df[date_col]
    )

    df["Year"] = df[date_col].dt.year

    df["Month"] = df[date_col].dt.month



    pivot = df.pivot_table(

        values=sales_col,

        index="Month",

        columns="Year",

        aggfunc="sum"
    )

    return pivot


# ==========================================
# Discount Profit Analysis
# ==========================================

def analyze_discount_profit(df, schema):

    discount_col = schema["discount"]

    profit_col = schema["profit"]


    if discount_col is None or profit_col is None:

        return "Required columns not available."


    result = df.groupby(

        discount_col

    )[profit_col].mean()

    return result

# ==========================================
# Product & Category Analysis
# ==========================================

def analyze_subcategory_profit(df, schema):

    subcategory_col = schema["subcategory"]

    profit_col = schema["profit"]

    discount_col = schema["discount"]

    sales_col = schema["sales"]

    if (
        subcategory_col is None
        or profit_col is None
        or discount_col is None
        or sales_col is None
    ):

        return "Required columns not available."


    result = df.groupby(

        subcategory_col

    ).agg({

        profit_col: "sum",

        discount_col: "mean",

        sales_col: "sum"
    })

    return result.sort_values(

        by=profit_col

    )


# ==========================================
# Top Revenue Products
# ==========================================

def analyze_top_revenue_products(df, schema):

    product_col = schema["product"]

    sales_col = schema["sales"]


    if product_col is None or sales_col is None:

        return "Required columns not available."


    result = df.groupby(

        product_col

    )[sales_col].sum()

    return result.sort_values(

        ascending=False

    ).head(10)


# ==========================================
# Top Loss Products
# ==========================================

def analyze_top_loss_products(df, schema):

    product_col = schema["product"]

    profit_col = schema["profit"]

    discount_col = schema["discount"]

    sales_col = schema["sales"]


    if (
        product_col is None
        or profit_col is None
        or discount_col is None
        or sales_col is None
    ):

        return "Required columns not available."

    result = df.groupby(

        product_col

    ).agg({

        profit_col: "sum",

        discount_col: "mean",

        sales_col: "sum"
    })

    return result.sort_values(

        by=profit_col

    ).head(10)

# ==========================================
# Regional Cross Analysis
# ==========================================

def analyze_worst_region_products(df, schema):

    region_col = schema["region"]

    subcategory_col = schema["subcategory"]

    profit_col = schema["profit"]

    sales_col = schema["sales"]

    discount_col = schema["discount"]


    if (
        region_col is None
        or subcategory_col is None
        or profit_col is None
        or sales_col is None
        or discount_col is None
    ):

        return "Required columns not available."


    cross = df.groupby(

        [region_col, subcategory_col]

    ).agg({

        profit_col: "sum",

        sales_col: "sum",

        discount_col: "mean"
    })

    result = cross.sort_values(

        by=profit_col

    ).head(10)

    return result


# ==========================================
# Best Region Products
# ==========================================

def analyze_best_region_products(df, schema):

    region_col = schema["region"]

    subcategory_col = schema["subcategory"]

    profit_col = schema["profit"]

    sales_col = schema["sales"]

    discount_col = schema["discount"]


    if (
        region_col is None
        or subcategory_col is None
        or profit_col is None
        or sales_col is None
        or discount_col is None
    ):

        return "Required columns not available."


    cross = df.groupby(

        [region_col, subcategory_col]

    ).agg({

        profit_col: "sum",

        sales_col: "sum",

        discount_col: "mean"
    })

    result = cross.sort_values(

        by=profit_col,

        ascending=False

    ).head(10)

    return result

# ==========================================
# Customer Analysis
# ==========================================

def analyze_customer_segmentation(df, schema):

    customer_col = schema["customer"]

    sales_col = schema["sales"]

    profit_col = schema["profit"]

    order_col = schema["order"]

    if (
        customer_col is None
        or sales_col is None
        or profit_col is None
        or order_col is None
    ):

        return "Required columns not available."

    customer = df.groupby(

        customer_col

    ).agg({

        sales_col: "sum",

        profit_col: "sum",

        order_col: "count"
    })

    customer.columns = [

        "Sales",

        "Profit",

        "Orders"
    ]

    customer["AOV"] = (

        customer["Sales"]

        /

        customer["Orders"]
    )

    return customer


# ==========================================
# Customer Lifetime Value
# ==========================================

def analyze_customer_clv(df, schema):

    customer_col = schema["customer"]

    sales_col = schema["sales"]

    profit_col = schema["profit"]

    order_col = schema["order"]


    if (
        customer_col is None
        or sales_col is None
        or profit_col is None
        or order_col is None
    ):

        return "Required columns not available."


    customer = df.groupby(

        customer_col

    ).agg({

        sales_col: "sum",

        profit_col: "sum",

        order_col: "count"
    })

    customer.columns = [

        "Sales",

        "Profit",

        "Orders"
    ]

    customer["AOV"] = (

        customer["Sales"]

        /

        customer["Orders"]
    )

    customer["CLV"] = (

        customer["AOV"]

        *

        customer["Orders"]
    )

    return customer


# ==========================================
# Segment Customer Type
# ==========================================

def analyze_segment_customer_type(df, schema):

    sales_col = schema["sales"]

    profit_col = schema["profit"]

    segment_col = detect_relevant_column(

        "segment column",

        df.columns
    )

    customer_type_col = detect_relevant_column(

        "customer type column",

        df.columns
    )


    if (
        sales_col is None
        or profit_col is None
        or segment_col is None
        or customer_type_col is None
    ):

        return "Required columns not available."


    result = df.groupby(

        [segment_col, customer_type_col]

    ).agg({

        sales_col: "sum",

        profit_col: "sum"
    })

    return result

# ==========================================
# Customer Machine Learning Analysis
# ==========================================

def train_customer_classifier(df, schema):

    # --------------------------------------
    # Dynamic Columns
    # --------------------------------------

    customer_col = schema["customer"]

    sales_col = schema["sales"]

    profit_col = schema["profit"]

    order_col = schema["order"]

    if (

        customer_col is None

        or sales_col is None

        or profit_col is None

        or order_col is None
    ):

        return "Required columns not available."

    # --------------------------------------
    # Customer Feature Engineering
    # --------------------------------------

    customer = df.groupby(

        customer_col

    ).agg({

        sales_col: "sum",

        profit_col: "sum",

        order_col: "count"
    })

    customer.columns = [

        "Monetary",

        "Profit",

        "Frequency"
    ]

    customer["AOV"] = (

        customer["Monetary"]

        /

        customer["Frequency"]
    )

    # --------------------------------------
    # Create Label
    # --------------------------------------

    threshold = customer[
        "Monetary"
    ].quantile(0.75)

    customer["High_Value"] = (

        customer["Monetary"]

        >= threshold

    ).astype(int)

    # --------------------------------------
    # Features and Target
    # --------------------------------------

    X = customer[

        [
            "Monetary",
            "Frequency",
            "AOV",
            "Profit"
        ]
    ]

    y = customer["High_Value"]

    # --------------------------------------
    # Train Test Split
    # --------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(

        X,

        y,

        test_size=0.2,

        random_state=42
    )

    # --------------------------------------
    # Standardization
    # --------------------------------------

    scaler = StandardScaler()

    X_train_scaled = scaler.fit_transform(
        X_train
    )

    X_test_scaled = scaler.transform(
        X_test
    )

    # --------------------------------------
    # Logistic Regression
    # --------------------------------------

    lr_model = LogisticRegression()

    lr_model.fit(

        X_train_scaled,

        y_train
    )

    lr_pred = lr_model.predict(

        X_test_scaled
    )

    print("===== Logistic Regression =====")

    print(

        classification_report(

            y_test,

            lr_pred
        )
    )

    # --------------------------------------
    # Random Forest
    # --------------------------------------

    rf_model = RandomForestClassifier(

        random_state=42
    )

    rf_model.fit(

        X_train,

        y_train
    )

    rf_pred = rf_model.predict(
        X_test
    )

    print("===== Random Forest =====")

    print(

        classification_report(

            y_test,

            rf_pred
        )
    )

    # --------------------------------------
    # Feature Importance
    # --------------------------------------

    importance = pd.DataFrame({

        "Feature": X.columns,

        "Importance":
        rf_model.feature_importances_
    })

    importance = importance.sort_values(

        "Importance",

        ascending=False
    )

    # --------------------------------------
    # Plot Feature Importance
    # --------------------------------------

    plt.figure(figsize=(8,5))

    plt.bar(

        importance["Feature"],

        importance["Importance"]
    )

    plt.title(
        "Feature Importance"
    )

    plt.xlabel("Feature")

    plt.ylabel("Importance")

    plt.show()

    # --------------------------------------
    # Top Predicted High Value Customers
    # --------------------------------------

    customer["Predicted_High_Value"] = (

        rf_model.predict(X)
    )

    top_customers = customer[

        customer["Predicted_High_Value"] == 1

    ].sort_values(

        "Monetary",

        ascending=False
    )

    return {

        "customer_data": customer,

        "feature_importance": importance,

        "top_customers": top_customers,

        "logistic_model": lr_model,

        "random_forest_model": rf_model
    }