# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ENKb1qd4r51Ke1QInKYr4fHchTbPu0xa
"""

# ==========================================
# Session Memory
# ==========================================

if "router_history" not in st.session_state:

    st.session_state.router_history = []

if "insight_history" not in st.session_state:

    st.session_state.insight_history = []

# ==========================================
# Title
# ==========================================

st.title(
    "AI Business Analytics Copilot"
)

st.write(
    "Upload a CSV file and ask business questions."
)


# ==========================================
# File Upload
# ==========================================

uploaded_file = st.file_uploader(
    "Upload CSV File",
    type=["csv"]
)


# ==========================================
# Run System
# ==========================================

if uploaded_file is not None:

    # Load Dataset
    df = pd.read_csv(
        uploaded_file,
        encoding="latin1"
    )

    st.success(
        "Dataset uploaded successfully."
    )

    # --------------------------------------
    # Data Cleaning
    # --------------------------------------

    with st.spinner(
        "Cleaning data..."
    ):

        df = clean_data(df)

    st.success(
        "Data cleaning completed."
    )

    # --------------------------------------
    # Show Dataset
    # --------------------------------------

    st.subheader("Cleaned Dataset")

    st.dataframe(df.head())

    # --------------------------------------
    # Business Question
    # --------------------------------------

    question = st.text_input(
        "Ask a business question"
    )

    # --------------------------------------
    # AI Agent
    # --------------------------------------

    if st.button("Analyze"):

        with st.spinner(
            "Generating AI insight..."
        ):

            answer = answer_business_question(

                question,

                df,

                st.session_state.router_history,

                st.session_state.insight_history
            )

        st.subheader(
            "AI Business Insight"
        )

        st.write(answer)