# -*- coding: utf-8 -*-
"""data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ERIPD-t7zvytta5BkcxDA_htB9xt45q
"""

import pandas as pd
import numpy as np

def check_missing_values(df):
    return df.isnull().sum()

def fill_missing_values(df):

    for col in df.columns:
        if df[col].dtype in ["int64", "float64"]:

            df[col] = df[col].fillna(
                df[col].mean()
            )
        else:
            df[col] = df[col].fillna(
                "Unknown"
            )

    return df

def remove_duplicates(df):
    return df.drop_duplicates()

def parse_datetime_columns(df):

    for col in df.columns:

        if any(

            x in col.lower()

            for x in [

                "date",

                "time",

                "month",

                "year"
            ]
        ):

            try:

                df[col] = pd.to_datetime(

                    df[col],

                    errors="coerce",

                    format="mixed"
                )

            except:

                pass

    return df

def detect_outliers(df):

    numeric_cols = df.select_dtypes(
        include=["int64", "float64"]
    ).columns

    outlier_summary = {}

    for col in numeric_cols:

        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)

        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        outliers = df[
            (df[col] < lower) |
            (df[col] > upper)
        ]

        outlier_summary[col] = len(outliers)

    return outlier_summary

def remove_invalid_values(df):

    numeric_cols = df.select_dtypes(
        include=["int64", "float64"]
    ).columns

    for col in numeric_cols:

        df = df[
            (df[col] < 1000000) &
            (df[col] > -1000000)
        ]

    return df

def standardize_text_columns(df):

    text_columns = df.select_dtypes(
        include="object"
    ).columns

    for col in text_columns:

        df[col] = (
            df[col]
            .astype(str)
            .str.strip()
            .str.title()
        )

    return df

# ==========================================
# Full Data Cleaning Pipeline
# ==========================================

def clean_data(df):

    print("Checking missing values...")
    print(check_missing_values(df))

    # Fill Missing Values
    df = fill_missing_values(df)

    # Parse Datetime
    df = parse_datetime_columns(df)

    # Remove Duplicates
    df = remove_duplicates(df)

    print("Detecting outliers...")
    print(detect_outliers(df))

    # Remove Invalid Values
    df = remove_invalid_values(df)

    # State Standardization
    df = standardize_text_columns(df)

    print("State cleaning completed.")

    return df