# -*- coding: utf-8 -*-
"""ai_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nztbsSsSF-p0AiN_1sVTz0tA28-q2Jo
"""

from openai import OpenAI

from analysis import *
from llm_analysis import *


# ==========================================
# OpenAI Client
# ==========================================

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)


# ==========================================
# Conversation Memory
# ==========================================

router_history = []

insight_history = []


# ==========================================
# LLM Router
# ==========================================

def route_question(question, router_history):

    prompt = f"""

    You are an AI business analytics router.

    Your job is to choose the SINGLE best tool
    for answering the user's question.

    Available tools:

    1. analyze_overall_sales
       -> overall sales and profit summary

    2. analyze_monthly_sales_trend
       -> time trend and seasonality analysis

    3. analyze_discount_profit
       -> discount and profit relationship

    4. analyze_subcategory_profit
       -> category and sub-category profitability

    5. analyze_top_revenue_products
       -> top-selling products

    6. analyze_top_loss_products
       -> worst-performing products

    7. analyze_worst_region_products
       -> worst region-product combinations

    8. analyze_best_region_products
       -> best region-product combinations

    9. analyze_customer_segmentation
       -> customer segmentation analysis

    10. analyze_customer_clv
        -> customer lifetime value analysis

    11. analyze_segment_customer_type
        -> segment and customer type analysis

    12. train_customer_classifier
        -> machine learning prediction
           for high-value customers

    Return ONLY the tool name.

    User Question:
    {question}

    """


    router_history.append({

        "role": "user",

        "content": prompt
    })

    response = client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=router_history
    )

    router_history.append({

        "role": "assistant",

        "content":
        response.choices[0].message.content
    })

    return response.choices[0].message.content.strip()


# ==========================================
# AI Business Agent
# ==========================================

def answer_business_question(

    question,

    df,

    router_history,

    insight_history
):

    # ======================================
    # Dynamic Schema
    # ======================================

    schema = {

        "sales": detect_relevant_column(
            "sales or revenue column",
            df.columns
        ) if any(
            x in c.lower()
            for c in df.columns
            for x in [
                "sales",
                "revenue",
                "income",
                "gmv",
                "amount"
            ]
        ) else None,

        "profit": detect_relevant_column(
            "profit column",
            df.columns
        ) if any(
            "profit" in c.lower()
            for c in df.columns
        ) else None,

        "discount": detect_relevant_column(
            "discount column",
            df.columns
        ) if any(
            "discount" in c.lower()
            for c in df.columns
        ) else None,

        "customer": detect_relevant_column(
            "customer column",
            df.columns
        ) if any(
            "customer" in c.lower()
            for c in df.columns
        ) else None,

        "order": detect_relevant_column(
            "order id column",
            df.columns
        ) if any(
            "order" in c.lower()
            for c in df.columns
        ) else None,

        "product": detect_relevant_column(
            "product column",
            df.columns
        ) if any(
            "product" in c.lower()
            for c in df.columns
        ) else None,

        "date": detect_relevant_column(
            "date column",
            df.columns
        ) if any(
            x in c.lower()
            for c in df.columns
            for x in [
                "date",
                "time",
                "month",
                "year"
            ]
        ) else None,

        "region": detect_relevant_column(
            "region column",
            df.columns
        ) if any(
            x in c.lower()
            for c in df.columns
            for x in [
                "region",
                "state",
                "city",
                "country"
            ]
        ) else None,

        "subcategory": detect_relevant_column(
            "subcategory column",
            df.columns
        ) if any(
            "sub" in c.lower()
            or "category" in c.lower()
            for c in df.columns
        ) else None
    }

    # ======================================
    # Route Question
    # ======================================

    tool_name = route_question(
        question,
        router_history
    )

    print(f"Selected Tool: {tool_name}")

    # ======================================
    # Tool Mapping
    # ======================================

    tools = {

        "analyze_overall_sales":
        analyze_overall_sales,

        "analyze_monthly_sales_trend":
        analyze_monthly_sales_trend,

        "analyze_discount_profit":
        analyze_discount_profit,

        "analyze_subcategory_profit":
        analyze_subcategory_profit,

        "analyze_top_revenue_products":
        analyze_top_revenue_products,

        "analyze_top_loss_products":
        analyze_top_loss_products,

        "analyze_worst_region_products":
        analyze_worst_region_products,

        "analyze_best_region_products":
        analyze_best_region_products,

        "analyze_customer_segmentation":
        analyze_customer_segmentation,

        "analyze_customer_clv":
        analyze_customer_clv,

        "analyze_segment_customer_type":
        analyze_segment_customer_type,

        "train_customer_classifier":
        train_customer_classifier
    }

    # ======================================
    # Invalid Tool
    # ======================================

    if tool_name not in tools:

        return "Sorry, I cannot answer this question."

    # ======================================
    # Run Analysis Tool
    # ======================================

    result = tools[tool_name](

        df,

        schema
    )

    # ======================================
    # Generate AI Insight
    # ======================================

    if tool_name in [

        "analyze_top_loss_products",

        "analyze_subcategory_profit",

        "analyze_top_revenue_products"
    ]:

        insight = generate_product_insight(

            result,

            question,

            insight_history
        )

    elif tool_name in [

        "analyze_customer_clv",

        "analyze_customer_segmentation",

        "analyze_segment_customer_type"
    ]:

        insight = generate_customer_insight(

            result,

            question,

            insight_history
        )

    elif tool_name in [

        "analyze_worst_region_products",

        "analyze_best_region_products"
    ]:

        insight = generate_regional_insight(

            result,

            question,

            insight_history
        )

    elif tool_name == "train_customer_classifier":

        insight = generate_ml_insight(

            result["feature_importance"],

            question,

            insight_history
        )

    else:

        insight = generate_business_insight(

            result,

            tool_name,

            question,

            insight_history
        )

    return insight

# ==========================================
# Show Conversation History
# ==========================================

def show_chat_history():

    return {

        "router_history":
        router_history,

        "insight_history":
        insight_history
    }