# -*- coding: utf-8 -*-
"""llm_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtGVhxZfQzhzO0nvr4FZSgEk3x0h-xRc
"""


from openai import OpenAI

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

# ==========================================
# General Business Insight
# ==========================================

def generate_business_insight(

    result,

    tool_name,

    question,

    insight_history
):

    prompt = f"""

    You are a senior business analyst.

    The following analysis result comes from:

    {tool_name}

    Important:

    This result may already be filtered,
    ranked,
    or sorted.

    Do NOT repeat obvious facts caused by filtering logic.

    Focus on:

    1. Business meaning
    2. Hidden patterns
    3. Root causes
    4. Strategic recommendations
    5. Operational risks

    User Question:
    {question}

    Data:

    {result}

    """

    insight_history.append({

        "role": "user",

        "content": prompt
    })

    response = client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=insight_history
    )

    insight_history.append({

        "role": "assistant",

        "content":
        response.choices[0].message.content
    })

    return response.choices[0].message.content


# ==========================================
# Product Analysis Insight
# ==========================================

def generate_product_insight(result, question, insight_history):

    prompt = f"""

    You are a product strategy analyst.

    User Question:
    {question}

    Analyze the following product performance data.

    Focus on:

    1. Loss-making products
    2. Discount impact
    3. Profitability structure
    4. Product optimization strategies

    Data:
    {result}

    """

    insight_history.append({

        "role": "user",

        "content": prompt
    })

    response = client.chat.completions.create(

          model="gpt-4.1-mini",

        messages=insight_history
    )

    insight_history.append({

       "role": "assistant",

        "content":
        response.choices[0].message.content
    })

    return response.choices[0].message.content


# ==========================================
# Regional Analysis Insight
# ==========================================

def generate_regional_insight(result, question, insight_history):

    prompt = f"""

    You are a regional business analyst.

    User Question:
    {question}

    Analyze the following regional business data.

    Focus on:

    1. High-risk regions
    2. Regional profitability patterns
    3. Discount issues
    4. Geographic business recommendations

    Data:
    {result}

    """

    insight_history.append({

        "role": "user",

        "content": prompt
    })

    response = client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=insight_history
    )

    insight_history.append({

        "role": "assistant",

        "content":
        response.choices[0].message.content
    })

    return response.choices[0].message.content


# ==========================================
# Customer Analysis Insight
# ==========================================

def generate_customer_insight(result, question, insight_history):

    prompt = f"""

    You are a customer analytics expert.

    User Question:
    {question}

    Analyze the following customer analysis results.

    Focus on:

    1. High-value customer behavior
    2. Customer profitability
    3. Customer retention risk
    4. Customer strategy recommendations

    Data:
    {result}

    """

    insight_history.append({

        "role": "user",

        "content": prompt
    })

    response = client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=insight_history
    )

    insight_history.append({

        "role": "assistant",

        "content":
        response.choices[0].message.content
    })

    return response.choices[0].message.content


# ==========================================
# Machine Learning Insight
# ==========================================

def generate_ml_insight(feature_importance, question, insight_history):

    prompt = f"""

    You are a machine learning business analyst.

    User Question:
    {question}

    Analyze the following feature importance results.

    Explain:

    1. Which features are most important
    2. Why these features matter
    3. Business implications
    4. Customer targeting strategies

    Feature Importance:
    {feature_importance}

    """

    insight_history.append({

        "role": "user",

        "content": prompt
    })

    response = client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=insight_history
    )

    insight_history.append({

        "role": "assistant",

        "content":
        response.choices[0].message.content
    })

    return response.choices[0].message.content


# ==========================================
# Executive Summary
# ==========================================

def generate_executive_summary(all_results):

    prompt = f"""

    You are a senior AI business consultant.

    Generate an executive summary for the following business analysis.

    Include:

    1. Major business risks
    2. Key opportunities
    3. Customer insights
    4. Product strategy
    5. Regional strategy
    6. Final recommendations

    Analysis Results:
    {all_results}

    """

    response = client.chat.completions.create(

        model="gpt-4.1-mini",

        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.choices[0].message.content